n1 = input('Digite algo: ')
print('Segue abaixo as informações!')
print('O seu tipo primitivo: ', type(n1))
print('É do tipo númerico? ', n1.isnumeric())
print('É do tipo Alfabético? ', n1.isalpha())
print('É do tipo Alfanumérico? ', n1.isalnum())
print('É só espaço? ', n1.isspace())
print('É só maiúsculo? ', n1.isupper())
print('É só minúsculo? ', n1.islower())
print('Está capitalizada? ', n1.istitle())

