times = ('Palmeiras', 'Corinthians', 'Fluminense', 'Athletico-PR', 'Flamengo', 'Internacional', 'Atlético-MG', 'Bragantino', 'Santos', 'São Paulo', 'Goiás', 'Botafogo', 'América-MG', 'Ceará', 'Coritiba', 'Avaí', 'Cuiabá', 'Fortaleza', 'Atlético-GO', 'Juventude')
print(f'Lista de times do Brasileirão: {times}')
print('-=' * 15)
print(f'Primeiros Colocados: {times[0:5]}')
print('-=' * 15)
print(f'Últimos Colocados: {times[16:21]}')
print('-=' * 15)
print(f'Ordem alfabética: {sorted(times)}')
print('-=' * 15)
print(f'O cuiabá está na {times.index("Cuiabá")+1}° posição.')
